---
deployment:
  tasks:
    - export DEPLOYPATH="${HOME}/public_html/"
    - /bin/echo "Deploying application to ${DEPLOYPATH}"
    - /bin/mkdir -p "${DEPLOYPATH}"
    - /bin/rsync -a --delete --exclude=".git/" --exclude=".cpanel/" --exclude=".cpanel.yml" ./ "${DEPLOYPATH}"
    - /bin/echo "Deployment finished successfully."
