---
# Update DEPLOYPATH to the absolute path of your public_html directory on cPanel
deployment:
  tasks:
    - export DEPLOYPATH=/home/<cpanel-user>/public_html/
    - /bin/mkdir -p "$DEPLOYPATH"
    - /bin/rsync -a --delete ./ "$DEPLOYPATH"
