deployment:
  tasks:
    - export DEPLOYPATH="${HOME}/public_html/"
    - /bin/echo "Deploying to ${DEPLOYPATH}"
    - /bin/mkdir -p "${DEPLOYPATH}"
    - /bin/cp -R * "${DEPLOYPATH}"
    - /bin/echo "Deployment completed successfully."
